# Generated by Django 6.0.5 on 2026-06-16 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PRX', 'Próximo'), ('LIV', 'En Vivo'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='PRX', max_length=3)),
                ('cupo_maximo', models.PositiveIntegerField(default=16)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos_organizados', to=settings.AUTH_USER_MODEL)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='torneos.videojuego')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
                ('esta_completa', models.BooleanField(default=False)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='torneos.torneo')),
            ],
        ),
    ]
