# Generated by Django 6.0.5 on 2026-06-16 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_j1', models.PositiveIntegerField(default=0)),
                ('puntaje_j2', models.PositiveIntegerField(default=0)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('FIN', 'Finalizado')], default='PEN', max_length=3)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='torneos.fase')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuentros_ganados', to=settings.AUTH_USER_MODEL)),
                ('jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_j1', to=settings.AUTH_USER_MODEL)),
                ('jugador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_j2', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='torneos.torneo')),
            ],
        ),
    ]
