# Generated by Django 5.2.7 on 2026-06-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_administrador_id_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='baneado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_ban',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='motivo_ban',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
