# Generated by Django 6.0.5 on 2026-06-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_administrador_id_alter_profile_id'),
        ('usuarios', '0003_profile_baneado_profile_fecha_ban_profile_motivo_ban_and_more'),
    ]

    operations = [
    ]
