# Generated by Django 6.0.6 on 2026-06-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profile_baneado_profile_fecha_ban_profile_motivo_ban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='strikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
