# Generated by Django 6.0.6 on 2026-06-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_merge_20260622_2129'),
        ('usuarios', '0004_profile_strikes'),
    ]

    operations = [
    ]
