# Generated by Django 6.0.6 on 2026-06-22 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='torneos.torneo'),
        ),
    ]
